name: safe_scan
description: An app alerting you on recalls for items you have bought.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  sleek_circular_slider: ^2.0.1
  r_dotted_line_border: ^0.1.1
  flutter_zoom_drawer: ^3.1.1
  logging: ^1.2.0
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  flare_flutter: ^3.0.2
  dio: ^5.4.0
  hive: ^2.0.4
  intl: ^0.19.0
  dartz: ^0.10.1
  get_it: ^7.1.3
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.9
  shimmer: ^3.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.10.6
  firebase_database: ^10.4.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  cloud_firestore: ^4.13.1
  http: ^1.2.0
  flutter_riverpod: ^2.0.0
  firebase_messaging: ^14.7.13
  share_plus: ^7.2.2
  google_generative_ai: ^0.2.1
  url_launcher: ^6.2.5
#  firebase_core_platform_interface: .0
#  firebase_database: ^10.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  share: ^2.0.4
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.1.6
  json_serializable: ^6.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.2
  hive_generator: ^2.0.1
  google_ml_kit: ^0.16.3
  permission_handler: ^11.2.0
  camera: ^0.10.0+4
  google_fonts: ^6.1.0


flutter_icons:
  android: true
  ios: true
  image_path_android: assets/image/launcher_icon/launcher_icon.png
  image_path_ios: assets/image/launcher_icon/launcher_icon.png
  min_sdk_android: 25
#  multiDexEnabled true
  web:
    generate: true
    image_path: assets/image/launcher_icon/launcher_icon.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: assets/image/launcher_icon/launcher_icon_4x.png
  color_dark: "#2F2F2F"
  image_dark: assets/image/launcher_icon/launcher_icon_4x.png
  android_gravity: center
  ios_content_mode: center
  web_imae_mode: center
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/launcher_icon/launcher_icon.png
    - assets/icons/
    - assets/loading.flr

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
